apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: userpartitions-by-account-{{ task.task_id }}.{{ ds }}.{{ task_instance.try_number }}
  namespace: default
spec:
  sparkConf:
    "spark.ui.port": "4045"
    "spark.eventLog.enabled": "false"
    "spark.hadoop.fs.s3a.access.key": "abhishek"
    "spark.hadoop.fs.s3a.secret.key": "choudhary123"
    "spark.hadoop.fs.s3a.endpoint": "http://minio:9000"
    "spark.hadoop.fs.s3n.impl": "org.apache.hadoop.fs.s3n.S3AFileSystem"
    "spark.hadoop.fs.s3n.fast.upload": "true"
    "spark.hadoop.mapreduce.fileoutputcommitter.algorithm.version": "2"
    "spark.hadoop.fs.s3a.connection.ssl.enabled": "false"
    "spark.hadoop.fs.s3a.path.style.access": "true"
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "pysparkexample:aws2"
  imagePullPolicy: Never
  mainApplicationFile: local:///app/pyspark_jobs/accountbypartition.py
  arguments:
    - {{ dag_run.conf.destination }}
    - f"{{ dag_run.conf.destination }}_account"
  sparkVersion: "3.1.1"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 0
    onFailureRetryInterval: 1
    onSubmissionFailureRetries: 0
    onSubmissionFailureRetryInterval: 1
  driver:
    coreRequest: "500m"
    coreLimit: "1000m"
    memory: "512m"
    labels:
      version: 3.1.1
    serviceAccount: spark
  executor:
    coreRequest: "250m"
    instances: 2
    memory: "512m"
    labels:
      version: 3.1.1