apiVersion: apps/v1
kind: Deployment
metadata:
  name: duckdb-bundle
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-duckdb-bundle
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-duckdb-bundle
    spec:   
      containers:
      - image: buntha/duckdb-bundle:0.0.3
        imagePullPolicy: Always
        name: duckdb-bundle
        ports:
        - containerPort: 8088
---
apiVersion: v1
kind: Service
metadata:
  name: duckdb-bundle
spec:
  ports:
    - port: 8088
      targetPort: 8088
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: app-duckdb-bundle