apiVersion: v2
name: mlflow-server
version: 0.1.6
appVersion: "1.30.0"
description: A Helm chart for MLFlow On Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)


home: https://mlflow.org/
icon: https://mlflow.org/images/MLflow-logo-final-white-TM.png
sources:
  - https://github.com/abhishek-ch/data-machinelearning-the-boring-way/tree/main/helm-charts
  - https://mlflow.org/
maintainers:
  - name: ABC
    email: abhishek.create@gmail.com
    url: https://github.com/abhishek-ch
dependencies:
- name: postgresql
  version: 11.9.6
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
keywords:
  - mlflow
  - machinelearning
  - mlops
  - "model tracking"
  - "model versioning"
  - "mlflow projects"
  - "model registry"