name: Validate Chart

on:
  # pull_request:
  #   paths:
  #     - helm-charts/**'
  push:
    branches:
      - infrastructure
      - main
      - dev

jobs:
  lint-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run helm-docs
        run: .github/helm-docs.sh
  install-chart:
    name: install-chart
    runs-on: ubuntu-latest
    needs:
      - lint-docs
    strategy:
      matrix:
        k8s:
          - v1.22.7
          - v1.23.6
          - v1.24.0
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Create kind ${{ matrix.k8s }} cluster
        uses: helm/kind-action@v1.2.0
        with:
          version: v0.13.0
          node_image: kindest/node:${{ matrix.k8s }}
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1
      - name: Add bitnami repo
        run: helm repo add bitnami https://charts.bitnami.com/bitnami
      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --chart-dirs=helm-charts --target-branch=main)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
      - name: Run chart-testing (lint and install)
        run: ct lint-and-install --chart-dirs=helm-charts --target-branch=main --helm-extra-args="--timeout=15m" --debug=true